<?xml version="1.0"?>
<!-- Definizione dei propulsori (thruster) del BlueROV2: link, joint e plugin -->
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    
  <!-- Mesh delle eliche: cw (orario) e ccw (antiorario) -->
  <xacro:property name="prop_mesh_cw" value="package://bluerov2_description/meshes/bluerov2_propcw.dae"/>
  <xacro:property name="prop_mesh_ccw" value="package://bluerov2_description/meshes/bluerov2_propccw.dae"/>
  <!-- Raggio e lunghezza della geometria dell'elica -->
  <xacro:property name="prop_r" value="0.05"/>
  <xacro:property name="prop_l" value="0.035"/>
  
  <!-- Macro del thruster: crea link, joint e plugin per un propulsore -->
  <xacro:macro name="thruster" params="thruster_id *origin">

    <link name="${ns}/thruster${thruster_id}">

      <visual>
        <geometry>
          <xacro:if value="${thruster_id in [1,2,5]}">
            <mesh filename="${prop_mesh_cw}"/>
          </xacro:if>
            <xacro:unless value="${thruster_id in [1,2,5]}">
            <mesh filename="${prop_mesh_ccw}"/>
          </xacro:unless>
        </geometry>
      </visual>
      
<!--        <collision>
            <origin rpy="0 ${PI/2} 0"/>
        <geometry>            
            <cylinder length="${prop_l}" radius="${prop_r}"/>
        </geometry>
      </collision>-->

     <inertial>
     <!-- L'asse del thruster è X; posizioniamo l'origine al centro geometrico -->
      <origin xyz="${prop_l/2} 0 0" rpy="0 0 0" />
      <!-- Massa dell'elica (prop_mass definita in bluerov2.xacro) -->
      <mass value="${prop_mass}" />
      <!-- Inerzia dell'elica approssimata come cilindro sottile -->
      <inertia  izz="${prop_mass*prop_r*prop_r / 4  + prop_mass*prop_l*prop_l / 12}" ixy="0.0"  ixz="0.0"
                iyy="${prop_mass*prop_r*prop_r / 4  + prop_mass*prop_l*prop_l / 12}" iyz="0.0"
                ixx="${prop_mass*prop_r*prop_r / 2}" />
    </inertial>
    </link>

    <!-- Giunto tra il link del thruster e il base_link del veicolo -->    
    <joint name="thruster${thruster_id}" type="continuous">
      <xacro:insert_block name="origin" />
      <xacro:if value="${thruster_id in [1,2,5]}">
        <axis xyz="1 0 0" />
      </xacro:if>
      <xacro:unless value="${thruster_id in [1,2,5]}">
        <axis xyz="-1 0 0" />
      </xacro:unless>
      <parent link="${ns}/base_link" />
      <child link="${ns}/thruster${thruster_id}" />
      <limits effort="-1" velocity="-1"/>
    </joint>

    <!-- Plugin di Ignition per controllare il thruster (comandi su topic ROS/Ignition) -->
<!--    <xacro:if value="$(arg simulation)"> -->
    <gazebo>
        <plugin
            filename="ignition-gazebo-thruster-system"
            name="ignition::gazebo::systems::Thruster">
            <namespace>${ns}</namespace>
            <joint_name>thruster${thruster_id}</joint_name>
            <topic>thruster${thruster_id}/cmd</topic>
            <!-- Coefficiente di spinta del propulsore (relazione forza-comando) -->
            <thrust_coefficient>0.011</thrust_coefficient>
            <!-- Densità del fluido (acqua), passata da bluerov2.xacro -->
            <fluid_density>${density}</fluid_density>
            <!-- Diametro dell'elica -->
            <propeller_diameter>${2*prop_r}</propeller_diameter>
            <!-- Controllo in velocità (true) invece che angolare -->
            <velocity_control>true</velocity_control>
            <use_angvel_cmd>false</use_angvel_cmd>
            <!-- Limiti del comando di spinta -->
            <max_thrust_cmd>40</max_thrust_cmd>
            <min_thrust_cmd>-40</min_thrust_cmd>
        </plugin>
      </gazebo>
<!--  </xacro:if> -->
</xacro:macro>

  <!-- Istanziazione di tutti e 6 i thruster con posizioni e orientazioni -->
    
  <xacro:thruster thruster_id="1">
    <origin xyz="0.1355 -0.1 -0.0725" rpy="0 0 0.7853981634"/>
  </xacro:thruster>
  
  <xacro:thruster thruster_id="2">
    <origin xyz="0.1355 0.1 -0.0725" rpy="0 0 -0.7853981634"/>
  </xacro:thruster>
  
  <xacro:thruster thruster_id="3">
    <origin xyz="-0.1475 -0.1 -0.0725" rpy="0 0 2.3561944902"/>
  </xacro:thruster>
  
  <xacro:thruster thruster_id="4">
    <origin xyz="-0.1475 0.1 -0.0725" rpy="0 0 -2.3561944902"/>
  </xacro:thruster>

  <xacro:thruster thruster_id="5">
    <origin xyz="0.0025 -0.1105 -0.005" rpy="0 -1.5707963268 0"/>
  </xacro:thruster>
  
  <xacro:thruster thruster_id="6">
    <origin xyz="0.0025 0.1105 -0.005" rpy="0 -1.5707963268 0"/>
  </xacro:thruster>

</robot>
